# Manually triggered IPFS release workflow
name: IPFS Release

on: workflow_dispatch

jobs:
  ipfs-release:
    strategy:
      matrix:
        node: ['20']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    # a safe guard to ensure that the workflow is only triggered on the main branch
    # if: github.ref == 'refs/heads/main'
    outputs:
      pinata_hash: '${{ steps.pinata.outputs.hash }}'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build

      - uses: phoenixlabsresearch/pinata-action@a3409e26f4cb859a2d9984109317caac53db5f68
        name: pinata
        id: pinata
        with:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_KEY: ${{ secrets.PINATA_SECRET_KEY }}
          PIN_ALIAS: 'app-beta-spark-${{ github.head_ref || github.ref }}'
          BUILD_LOCATION: 'packages/app/dist'
          CID_VERSION: 1
